### ISSUE TITLE
Some less used Aggregations are breaking QueryBuilder

### ISSUE THREAD

**Issue by dg-nvm** [VictoriaMetrics/victoriametrics-datasource#152]
Some of the less used aggregations are missing like share or median, which means if you write query like this:

`median by(cloud) (median_over_time(test{}[$__interval]))`

it will break if you switch to CodeBuilder:

![image](https://github.com/VictoriaMetrics/grafana-datasource/assets/50369002/8ab193e1-2ee8-474a-a786-f6f15cb1d12e)

If you use supported aggregation (avg) it will be ok:

![image](https://github.com/VictoriaMetrics/grafana-datasource/assets/50369002/18de4b1f-a6ee-41cb-904a-edee44b7edac)

And median [is indeed Aggregate Function](https://docs.victoriametrics.com/metricsql/#median) but I believe it's missing in lazer-metricsql

**Comment by dmitryk-dk** [comment]
Hi @dg-nvm ! The issue was fixed in the [release](https://github.com/VictoriaMetrics/victoriametrics-datasource/releases/tag/v0.8.4). Close as resolved
