### ISSUE TITLE
datasource not working with Grafana versions below `10.0.0`

### ISSUE THREAD

**Issue by Loori-R** [VictoriaMetrics/victoriametrics-datasource#159]
When attempting to open datasource settings in Grafana versions below `10.0.0`, an error occurs: 
![image](https://github.com/VictoriaMetrics/grafana-datasource/assets/29711459/d28c2081-83f9-4d4b-b3a2-4d64d7e84f7b)

**Comment by SQLJames** [comment]
@Loori-R, Can you provide your helm values for grafana, specifically how you are loading the plugin and where you are seeing that error?

**Comment by Loori-R** [comment]
@SQLJames I do not use Helm to configure Grafana. Instead, I launched Grafana manually and specified the plugin folder in Grafana's configs. The error appears when I go to the datasource settings page.

**Comment by hagen1778** [comment]
The fix was added in https://github.com/VictoriaMetrics/victoriametrics-datasource/commit/0f198cefba92bf30c3b5156caa24c19181c97aa4 and will be included into the next release
