### ISSUE TITLE
Label join function does not work when separator is not ',' in Builder mode

### ISSUE THREAD

**Issue by chenlujjj** [VictoriaMetrics/victoriametrics-datasource#162]
![image](https://github.com/VictoriaMetrics/grafana-datasource/assets/17081528/664518a8-67f4-44a8-9b12-9b22c25f4fbc)
As you can see from the above image, the query is invalid when the separator is '-'.

Seems it only works when separator is ','

**Comment by dmitryk-dk** [comment]
Hi @chenlujjj ! The issue was fixed in the [release](https://github.com/VictoriaMetrics/victoriametrics-datasource/releases/tag/v0.8.4). Close as resolved
