### ISSUE TITLE
adhoc and median function result in unexpected error reuqest

### ISSUE THREAD

**Issue by yincongcyincong** [VictoriaMetrics/victoriametrics-datasource#175]
when i write a median function metric. 
the adhoc and the metrics result in an error request.

![image](https://github.com/VictoriaMetrics/grafana-datasource/assets/24344673/c97e4a21-62d3-49e8-b3c7-2e2ebb1c523c)

**Comment by dmitryk-dk** [comment]
Hi @yincongcyincong ! The issue was fixed in the [release](https://github.com/VictoriaMetrics/victoriametrics-datasource/releases/tag/v0.8.4). Close as resolved
