### ISSUE TITLE
Cannot use WITH templates on provisioned datasource

### ISSUE THREAD

**Issue by ulope** [VictoriaMetrics/victoriametrics-datasource#190]
Trying to add a WITH template to a dashboard using a provisioned VM datasource is rejected with the error `Cannot update read-only data source`.

**Comment by hagen1778** [comment]
Hi @ulope! This is expected.
WITH templates are stored within dashboard JSON model. And Grafana doesn't allow to change this model, or do any other changes to the dashboard if it was provisioned.
