### ISSUE TITLE
backend: retry datasource requests for trivial network errors

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/victoriametrics-datasource#193]
See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6712

In the issue above, request sent by Grafana failed because of EOF error. There could be many reasons why plugin faced the EOF error, but the sensible thing to do would be to retry such trivial network errors.

For the reference, other VM components like vmalert already retry requests for such errors.

**Comment by hagen1778** [comment]
> Hi @hagen1778 ! Should we use the exact mechanism in the [Victorialogs](https://github.com/VictoriaMetrics/victorialogs-datasource) data source?

Yes

**Comment by hagen1778** [comment]
plugin should retry trivial network errors like "unexpected EOF" or "broken pipe" in https://github.com/VictoriaMetrics/victoriametrics-datasource/pull/194. This change will be included into the next release.

**Comment by hagen1778** [comment]
@dmitryk-dk can we make release soon?

**Comment by dmitryk-dk** [comment]
> @dmitryk-dk can we make release soon?

Yeah, i think will do it today little bit later

**Comment by dmitryk-dk** [comment]
Hi @hagen1778 ! Release was published with the latest changes. The fix was included into [v0.9.0 release](https://github.com/VictoriaMetrics/grafana-datasource/releases/tag/v0.9.0).

**Comment by dmitryk-dk** [comment]
Hi @hagen1778 ! The same behavior was ported to the [victorialogs-datasource](https://github.com/VictoriaMetrics/victorialogs-datasource) in the [v0.4.0](https://github.com/VictoriaMetrics/victorialogs-datasource/releases/tag/v0.4.0) release
