### ISSUE TITLE
unsupported function \"label_values\"" when query type is label values in dashboard variable setting

### ISSUE THREAD

**Issue by chenlujjj** [VictoriaMetrics/victoriametrics-datasource#198]
request payload:
<img width="366" alt="image" src="https://github.com/user-attachments/assets/31414268-58a8-4356-a11c-5d98e3554c0f">

response:
![image](https://github.com/user-attachments/assets/74aeb330-47cc-4e06-a8d1-d94b8c648cc6)

I think there are several problems here:
* unsupported function `label_values` is used
* in the request payload, there is no metric name
* the request uses `/api/v1/series` API, not the label value API

**Comment by chenlujjj** [comment]
Hi, @dmitryk-dk , any progress of this issue ?

**Comment by Loori-R** [comment]
Hi @chenlujjj, we are currently working on this issue and expect to resolve it soon.

**Comment by dmitryk-dk** [comment]
Hi @chenlujjj ! Can you try to check the latest [release](https://github.com/VictoriaMetrics/victoriametrics-datasource/releases/tag/v0.9.1)?

**Comment by chenlujjj** [comment]
Thanks @dmitryk-dk , the problem got resolved after upgrading the datasource plugin

**Comment by dmitryk-dk** [comment]
Close the issue as resolved.
