### ISSUE TITLE
Sluggish label filtering when thousands of possible label values

### ISSUE THREAD

**Issue by 0lionelzhang0** [VictoriaMetrics/victoriametrics-datasource#206]
Hello!

Thank you for this Grafana plugin, it has been immensely useful!

While using the query "Builder" and using the dropdown to add a new label, the performance seems to be sluggish when there are thousands of possible label values. More specifically, I choose a label name, then start typing the label value and since there are thousands of label values to filter through it appears to slow things down. Is there a way to limit the number of returned label values as one types it in?

For what it's worth, I don't experience any performance slowdowns when using the "Metrics browser" under "Code" instead of "Builder".

Thanks,
Lionel

**Comment by Loori-R** [comment]
Hello, @0lionelzhang0!

You can adjust the limits on the data source settings page. At the end of the settings, there is a **Limits** section where you can restrict the number of returned label values.
 
This functionality is supported starting from version [v0.4.0](https://github.com/VictoriaMetrics/victoriametrics-datasource/releases/tag/v0.4.0). You can find more details in the release of version [v0.4.0](https://github.com/VictoriaMetrics/victoriametrics-datasource/releases/tag/v0.4.0) and in the description of the [pull request #91](https://github.com/VictoriaMetrics/victoriametrics-datasource/pull/91).

I hope this helps resolve your issue.

**Comment by 0lionelzhang0** [comment]
Thank you @Loori-R!
