### ISSUE TITLE
explore inspector doesn't work

### ISSUE THREAD

**Issue by yincongcyincong** [VictoriaMetrics/victoriametrics-datasource#215]
no request and response.
https://github.com/user-attachments/assets/03aed121-7fb5-40f1-9e25-e3ac8a43bf5b

**Comment by dmitryk-dk** [comment]
HI! The issue should be fixed in the [release](https://github.com/VictoriaMetrics/victoriametrics-datasource/releases/tag/v0.10.2). Please reopen the issue if you find any problems
