### ISSUE TITLE
The variable `$__interval` is templated to an incorrect value during annotation query

### ISSUE THREAD

**Issue by Haleygo** [VictoriaMetrics/victoriametrics-datasource#217]
**To reproduce**:
Adding an annotation with following query:
`sum(changes(vm_app_start_timestamp{job=~"$job", instance=~"$instance"}[$__interval])) by(job)`
and execute this query over a big time range like 24h, see [this example](https://play-grafana.victoriametrics.com/d/LzldHAVnz_vm/victoriametrics-vmalert-vm?orgId=1&var-ds=P38648FE0F8C5BEA2&var-job=monitoring%2Fprometheus-benchmark-vmalert&var-instance=All&var-group=All&var-topk=5&from=1729785600000&to=1729871999000) on playground.
VM-datasource sets the `$__interval` to 60s, but the actual step for the returned results is 15m(probably limited by returned data points), resulting in missed restart events.
<img width="2499" alt="image" src="https://github.com/user-attachments/assets/71f5e1f0-5d7c-4140-8865-cf5c64ceb760">

**Expected result**:
`$__interval` should be templated as the actual `step` arg in the query request to datasource as prometheus datasource, see [this example](https://play-grafana.victoriametrics.com/d/LzldHAVnz/victoriametrics-vmalert?orgId=1&from=1729785600000&to=1729871999000&var-ds=PE8D8DB4BEE4E4B22&var-job=monitoring%2Fprometheus-benchmark-vmalert&var-instance=All&var-group=All&var-topk=5).
<img width="2503" alt="image" src="https://github.com/user-attachments/assets/ea5a292a-b176-4696-a0b8-e9ce89cdc76f">

**Comment by dmitryk-dk** [comment]
HI @Haleygo ! The issue was fixed in the new [v0.10.3](https://github.com/VictoriaMetrics/victoriametrics-datasource/releases/tag/v0.10.3) release. Close as solved. Fill free to reopen if you find any problem
