### ISSUE TITLE
Explore: value show undefined

### ISSUE THREAD

**Issue by yincongcyincong** [VictoriaMetrics/victoriametrics-datasource#218]
![image](https://github.com/user-attachments/assets/1946e4e0-973b-4c61-bc3b-30ec1b30fe19)
after click pretty query
![image](https://github.com/user-attachments/assets/6b41b2a3-cd26-48ed-a441-1c3c2a693579)
values shows undefined

**Comment by dmitryk-dk** [comment]
HI! The issue should be fixed in the [release](https://github.com/VictoriaMetrics/victoriametrics-datasource/releases/tag/v0.10.2). Please reopen the issue if you find any problems
