### ISSUE TITLE
Regression 0.10.2: Panels with multiple queries stuck loading

### ISSUE THREAD

**Issue by jan-di** [VictoriaMetrics/victoriametrics-datasource#223]
Hello, 

v0.10.2 seems to introduce a regression. On Grafana panels that have more than one visible query, the query requests never get done and the panel is loading indefinitely. Each individual queries are working fine, if viewed alone. See example below.

Using latest Grafana version (v11.3.0+security-01)
With datasourcev0.10.1 it does work as expected. Probably its caused by the changes in https://github.com/VictoriaMetrics/victoriametrics-datasource/pull/216.

Example:
![gif1](https://github.com/user-attachments/assets/98fd777d-625d-4b46-aaa0-db24abf17a6e)

The respective network requests seem to be cancelled by the client before they are finished:
<img width="955" alt="grafik" src="https://github.com/user-attachments/assets/71ac2bd1-22d4-4aef-ac5f-b6e0f9ba00ad">

**Comment by frli4797** [comment]
I have the same problem. I can confirm rolling back to v0.10.0 fixes this.

**Comment by matejsp** [comment]
Same problem here ... I see in logs. 
```
deprecationWarning.ts:14 [Deprecation warning] DataSource victoriametrics-datasource: templateSrv.getAdhocFilters is deprecated. Use filters property on the request (DataQueryRequest). Or if this is called from interpolateVariablesInQueries or applyTemplateVariables it is passed as a new argument instead
```

**Comment by dmitryk-dk** [comment]
Hi @jan-di ! The issue was fixed in the new [v0.10.3](https://github.com/VictoriaMetrics/victoriametrics-datasource/releases/tag/v0.10.3) release. Could you please check it?

**Comment by dmitryk-dk** [comment]
Close issue as solved fill free to reopen if you find any problems with new relase

**Comment by jan-di** [comment]
Works again. Thank you for the quick solution :-)
