### ISSUE TITLE
when query is number. nothing to show

### ISSUE THREAD

**Issue by yincongcyincong** [VictoriaMetrics/victoriametrics-datasource#231]
when query is number and query number is two or more. nothing to show and the query is blocked.
![image](https://github.com/user-attachments/assets/a6c2ea27-a5ad-4b6a-a120-8a46b248cba6)
but prometheus datasource can show the numbers.
![image](https://github.com/user-attachments/assets/91092ef4-152e-4967-b945-5df361fb24bf)

**Comment by hagen1778** [comment]
@yincongcyincong I can't reproduce this at https://play-grafana.victoriametrics.com/. Can you?

From your screenshot it looks like query just doesn't return any response: the spin-wheel is spinning constantly. So it is likely datasource backend doesn't respond. What network tab tells you?

**Comment by yincongcyincong** [comment]
i think the newest version fixed it. i would close it. @hagen1778
