### ISSUE TITLE
Query results in the dashboard don't follow the time range used

### ISSUE THREAD

**Issue by bluewyn** [VictoriaMetrics/victoriametrics-datasource#236]
on query explorer, last 5 minutes should be only 1 controller pod
<img width="1188" alt="Screenshot 2024-12-09 at 14 48 13" src="https://github.com/user-attachments/assets/6bb820ba-0b15-408c-9a78-b6078f62ec07">

but when the query was run on the Grafana dashboard, it also showed the controller pods that had been destroyed, not just the current pod.
<img width="999" alt="Screenshot 2024-12-09 at 14 47 04" src="https://github.com/user-attachments/assets/89cebf46-12f8-4a60-ba72-09e15cefe6bb">

In addition to having the same time range, the queries between explorer and dashboard are the same but have different outputs as I mentioned earlier.

**Environment**
Grafana version: v10.4.14 (stable version)
VM Datasource version:
<img width="877" alt="Screenshot 2024-12-09 at 14 19 43" src="https://github.com/user-attachments/assets/3fff1285-8608-4285-a889-ee76ff7ae3db">

I have compared it with Prometheus datasource and the Prometheus grafana dashboard follow the time range applied
<img width="1003" alt="Screenshot 2024-12-09 at 15 34 37" src="https://github.com/user-attachments/assets/1ed46d38-dd48-4f75-93cc-7fdb95bd0954">

**Comment by hagen1778** [comment]
Closing as answered.
